### PR TITLE
Pull request for windows command 

### PR DESCRIPTION
**Pull request by deepalimayekar**

### CODE REVIEW

**Comment by deepalimayekar** [comment]
@arey  please accept

**Comment by arey** [comment]
mvnw without the .cmd extension should work on Windows. Isn't it?

**Comment by deepalimayekar** [comment]
> mvnw without the .cmd extension should work on Windows. Isn't it?

no, it unfortunately did not work and then only after using the above command it worked.

**Comment by arey** [comment]
Thanks a lot @deepalimayekar for your contribution

**Pull request merged**
